export const MANAGEMENT_BASE_PAGE = "";
export const MANAGEMENT_PROJECTS_BASE_PAGE = `${MANAGEMENT_BASE_PAGE}/project`;
const MANAGEMENT_PAGES = {
  HOME_PAGE: `${MANAGEMENT_BASE_PAGE}`,
  MESSAGES_PAGE: `${MANAGEMENT_BASE_PAGE}/messages`,
  TASKS_PAGE: `${MANAGEMENT_BASE_PAGE}/tasks`,
  MEMBERS_PAGE: `${MANAGEMENT_BASE_PAGE}/members`,
  SETINGS_PAGE: `${MANAGEMENT_BASE_PAGE}/settings`,
  MOBILE_APP_PAGE: `${MANAGEMENT_PROJECTS_BASE_PAGE}/mobile_app`,
  WEBSITE_REDESIGN_PAGE: `${MANAGEMENT_PROJECTS_BASE_PAGE}/website_redesign`,
  DESIGN_PAGE: `${MANAGEMENT_PROJECTS_BASE_PAGE}/design_system_page`,
  WIREFRAME_PAGE: `${MANAGEMENT_PROJECTS_BASE_PAGE}/wireframe_page`,
};

export { MANAGEMENT_PAGES };